### ISSUE TITLE
Troubles when installing on Hikey

### ISSUE THREAD

**Issue by Chunosov** [ctuning/ck-request-asplos18-mobilenets-tvm-arm#9]
- [x] 1) Remove `opencv-python` from installations scripts `ck-mxnet/lib-mxnet-0.11.0-cpu/install.sh` and `ck-mxnet/lib-mxnet-master-cpu/scripts.linux/install.sh` (https://github.com/ctuning/ck-request-asplos18-mobilenets-tvm-arm/issues/9#issuecomment-418604420)
- [x] 2) Check is `jupiter` is really neede by the library and think about removing it frome those scripts too (https://github.com/ctuning/ck-request-asplos18-mobilenets-tvm-arm/issues/9#issuecomment-418604420)
- [x] 3) Add `requests` dependency in those scripts. (https://github.com/ctuning/ck-request-asplos18-mobilenets-tvm-arm/issues/9#issuecomment-418605244)
- [x] 4) Fix git cloning of `nnvm` (https://github.com/ctuning/ck-request-asplos18-mobilenets-tvm-arm/issues/9#issuecomment-418605834)

**Comment by Chunosov** [comment]
to 1) seems `opencv` is not required by the library itself, it only mentioned in comments:
```
nchunosov@hikey962:~/CK-TOOLS/mxnet-cpu-gcc-7.2.0-linux-64/src/python$ grep -rn '.' -e 'opencv'
./mxnet/image/image.py:201:        http://docs.opencv.org/master/da/d54/group__imgproc__transform.html.
./mxnet/image/image.py:264:        http://docs.opencv.org/master/da/d54/group__imgproc__transform.html.
Binary file ./mxnet/image/image.pyc matches
```

**Comment by Chunosov** [comment]
to 3) there is some hack about importing `requests` in the library:
```
try:
    import requests
except ImportError:
    class requests_failed_to_import(object):
        pass
    requests = requests_failed_to_import
```
but we really need this package in order to install mxnetmodels.
Now we have do manually `pip install requests` before `ck install mxnetmodel-mobilenet-1.0`

**Comment by Chunosov** [comment]
to 4) now we can't  clone `nnvm` package from `master` branch because they've removed the required commit of `tvm` submodule (?!):
```
Cloning package from https://github.com/dmlc/nnvm.git/ ...
Cloning into 'src'...
remote: Counting objects: 3900, done.
remote: Total 3900 (delta 0), reused 0 (delta 0), pack-reused 3900
Receiving objects: 100% (3900/3900), 1.16 MiB | 1.69 MiB/s, done.
Resolving deltas: 100% (2354/2354), done.
Submodule 'dmlc-core' (https://github.com/dmlc/dmlc-core) registered for path 'dmlc-core'
Submodule 'tvm' (https://github.com/dmlc/tvm) registered for path 'tvm'
Cloning into '/home/nchunosov/CK-TOOLS/lib-tvm-nnvm-llvm-6.0.0-linux-64/src/dmlc-core'...
remote: Counting objects: 5103, done.        
remote: Compressing objects: 100% (37/37), done.        
remote: Total 5103 (delta 40), reused 60 (delta 35), pack-reused 5031        
Receiving objects: 100% (5103/5103), 1.26 MiB | 1.73 MiB/s, done.
Resolving deltas: 100% (3065/3065), done.
Cloning into '/home/nchunosov/CK-TOOLS/lib-tvm-nnvm-llvm-6.0.0-linux-64/src/tvm'...
remote: Counting objects: 23597, done.        
remote: Compressing objects: 100% (14/14), done.        
remote: Total 23597 (delta 3), reused 2 (delta 2), pack-reused 23581        
Receiving objects: 100% (23597/23597), 6.83 MiB | 3.72 MiB/s, done.
Resolving deltas: 100% (15474/15474), done.
Submodule path 'dmlc-core': checked out '42823a731bdb2c22aa44775c0937466046400c02'
error: no such remote ref 4472b078d0abb20ff7f7bdab5ef2e42c33e90f87
Fetched in submodule path 'tvm', but it did not contain 4472b078d0abb20ff7f7bdab5ef2e42c33e90f87. Direct fetching of that commit failed.
Error: git cloning failed!
```

**Comment by Chunosov** [comment]
1) fixed here https://github.com/ctuning/ck-mxnet/pull/1
2) stayed as it was for now
3) fixed here https://github.com/ctuning/ck-mxnet/pull/1

**Comment by Chunosov** [comment]
4. fixed by this https://github.com/ctuning/ck-tvm/pull/1 and this https://github.com/ctuning/ck-request-asplos18-mobilenets-tvm-arm/pull/10
